version: "3.6"

services:
  dev:
    image: rust
    container_name: aworld-data-dev
    volumes:
      - ..:/app
    tty: true
    ports:
      - "34254:34254/udp"
      - "34253:34253/udp"
    working_dir: /app
    networks:
      app_net:
        ipv4_address: 172.16.238.10
    depends_on:
      - "mysql"
    # command: cargo run --bin server --release

  mysql:
    container_name: aworld-data-sql
    image: mysql:5.7.27
    environment:
      MYSQL_ROOT_PASSWORD: "ourworld"
    restart: 'always'
    ports:
      - "3306:3306"
    networks:
      app_net:
        ipv4_address: 172.16.238.11

networks:
  app_net:
    name: back_end_net
    ipam:
      driver: default
      config:
        - subnet: "172.16.238.0/24"
